/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as ChangelogRouteImport } from './routes/changelog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as VsMarkerRouteImport } from './routes/vs.marker'
import { Route as RTokenRouteImport } from './routes/r.$token'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'
import { Route as DashboardReferralsRouteImport } from './routes/dashboard.referrals'
import { Route as DashboardRedeemRouteImport } from './routes/dashboard.redeem'
import { Route as DashboardInstallRouteImport } from './routes/dashboard.install'
import { Route as DashboardBillingRouteImport } from './routes/dashboard.billing'
import { Route as DashboardAdminRouteImport } from './routes/dashboard.admin'
import { Route as DashboardAccountRouteImport } from './routes/dashboard.account'
import { Route as DashboardProjectsNewRouteImport } from './routes/dashboard.projects.new'
import { Route as DashboardProjectsProjectIdRouteImport } from './routes/dashboard.projects.$projectId'
import { Route as DashboardAdminUsersRouteImport } from './routes/dashboard.admin.users'
import { Route as DashboardAdminCodesRouteImport } from './routes/dashboard.admin.codes'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api.public.stripe-webhook'
import { Route as ApiPublicFeedbackRouteImport } from './routes/api.public.feedback'
import { Route as ApiPublicWidgetConfigTokenRouteImport } from './routes/api.public.widget-config.$token'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ChangelogRoute = ChangelogRouteImport.update({
  id: '/changelog',
  path: '/changelog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const VsMarkerRoute = VsMarkerRouteImport.update({
  id: '/vs/marker',
  path: '/vs/marker',
  getParentRoute: () => rootRouteImport,
} as any)
const RTokenRoute = RTokenRouteImport.update({
  id: '/r/$token',
  path: '/r/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardReferralsRoute = DashboardReferralsRouteImport.update({
  id: '/dashboard/referrals',
  path: '/dashboard/referrals',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRedeemRoute = DashboardRedeemRouteImport.update({
  id: '/dashboard/redeem',
  path: '/dashboard/redeem',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardInstallRoute = DashboardInstallRouteImport.update({
  id: '/dashboard/install',
  path: '/dashboard/install',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardBillingRoute = DashboardBillingRouteImport.update({
  id: '/dashboard/billing',
  path: '/dashboard/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/dashboard/admin',
  path: '/dashboard/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAccountRoute = DashboardAccountRouteImport.update({
  id: '/dashboard/account',
  path: '/dashboard/account',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProjectsNewRoute = DashboardProjectsNewRouteImport.update({
  id: '/dashboard/projects/new',
  path: '/dashboard/projects/new',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProjectsProjectIdRoute =
  DashboardProjectsProjectIdRouteImport.update({
    id: '/dashboard/projects/$projectId',
    path: '/dashboard/projects/$projectId',
    getParentRoute: () => rootRouteImport,
  } as any)
const DashboardAdminUsersRoute = DashboardAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminCodesRoute = DashboardAdminCodesRouteImport.update({
  id: '/codes',
  path: '/codes',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe-webhook',
  path: '/api/public/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFeedbackRoute = ApiPublicFeedbackRouteImport.update({
  id: '/api/public/feedback',
  path: '/api/public/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicWidgetConfigTokenRoute =
  ApiPublicWidgetConfigTokenRouteImport.update({
    id: '/api/public/widget-config/$token',
    path: '/api/public/widget-config/$token',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/changelog': typeof ChangelogRoute
  '/demo': typeof DemoRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/admin': typeof DashboardAdminRouteWithChildren
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/install': typeof DashboardInstallRoute
  '/dashboard/redeem': typeof DashboardRedeemRoute
  '/dashboard/referrals': typeof DashboardReferralsRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/r/$token': typeof RTokenRoute
  '/vs/marker': typeof VsMarkerRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/public/feedback': typeof ApiPublicFeedbackRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/dashboard/admin/codes': typeof DashboardAdminCodesRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersRoute
  '/dashboard/projects/$projectId': typeof DashboardProjectsProjectIdRoute
  '/dashboard/projects/new': typeof DashboardProjectsNewRoute
  '/api/public/widget-config/$token': typeof ApiPublicWidgetConfigTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/changelog': typeof ChangelogRoute
  '/demo': typeof DemoRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/admin': typeof DashboardAdminRouteWithChildren
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/install': typeof DashboardInstallRoute
  '/dashboard/redeem': typeof DashboardRedeemRoute
  '/dashboard/referrals': typeof DashboardReferralsRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/r/$token': typeof RTokenRoute
  '/vs/marker': typeof VsMarkerRoute
  '/dashboard': typeof DashboardIndexRoute
  '/api/public/feedback': typeof ApiPublicFeedbackRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/dashboard/admin/codes': typeof DashboardAdminCodesRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersRoute
  '/dashboard/projects/$projectId': typeof DashboardProjectsProjectIdRoute
  '/dashboard/projects/new': typeof DashboardProjectsNewRoute
  '/api/public/widget-config/$token': typeof ApiPublicWidgetConfigTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/changelog': typeof ChangelogRoute
  '/demo': typeof DemoRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/dashboard/account': typeof DashboardAccountRoute
  '/dashboard/admin': typeof DashboardAdminRouteWithChildren
  '/dashboard/billing': typeof DashboardBillingRoute
  '/dashboard/install': typeof DashboardInstallRoute
  '/dashboard/redeem': typeof DashboardRedeemRoute
  '/dashboard/referrals': typeof DashboardReferralsRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/r/$token': typeof RTokenRoute
  '/vs/marker': typeof VsMarkerRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/api/public/feedback': typeof ApiPublicFeedbackRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/dashboard/admin/codes': typeof DashboardAdminCodesRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersRoute
  '/dashboard/projects/$projectId': typeof DashboardProjectsProjectIdRoute
  '/dashboard/projects/new': typeof DashboardProjectsNewRoute
  '/api/public/widget-config/$token': typeof ApiPublicWidgetConfigTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/changelog'
    | '/demo'
    | '/login'
    | '/signup'
    | '/dashboard/account'
    | '/dashboard/admin'
    | '/dashboard/billing'
    | '/dashboard/install'
    | '/dashboard/redeem'
    | '/dashboard/referrals'
    | '/legal/privacy'
    | '/legal/terms'
    | '/r/$token'
    | '/vs/marker'
    | '/dashboard/'
    | '/api/public/feedback'
    | '/api/public/stripe-webhook'
    | '/dashboard/admin/codes'
    | '/dashboard/admin/users'
    | '/dashboard/projects/$projectId'
    | '/dashboard/projects/new'
    | '/api/public/widget-config/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/changelog'
    | '/demo'
    | '/login'
    | '/signup'
    | '/dashboard/account'
    | '/dashboard/admin'
    | '/dashboard/billing'
    | '/dashboard/install'
    | '/dashboard/redeem'
    | '/dashboard/referrals'
    | '/legal/privacy'
    | '/legal/terms'
    | '/r/$token'
    | '/vs/marker'
    | '/dashboard'
    | '/api/public/feedback'
    | '/api/public/stripe-webhook'
    | '/dashboard/admin/codes'
    | '/dashboard/admin/users'
    | '/dashboard/projects/$projectId'
    | '/dashboard/projects/new'
    | '/api/public/widget-config/$token'
  id:
    | '__root__'
    | '/'
    | '/changelog'
    | '/demo'
    | '/login'
    | '/signup'
    | '/dashboard/account'
    | '/dashboard/admin'
    | '/dashboard/billing'
    | '/dashboard/install'
    | '/dashboard/redeem'
    | '/dashboard/referrals'
    | '/legal/privacy'
    | '/legal/terms'
    | '/r/$token'
    | '/vs/marker'
    | '/dashboard/'
    | '/api/public/feedback'
    | '/api/public/stripe-webhook'
    | '/dashboard/admin/codes'
    | '/dashboard/admin/users'
    | '/dashboard/projects/$projectId'
    | '/dashboard/projects/new'
    | '/api/public/widget-config/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChangelogRoute: typeof ChangelogRoute
  DemoRoute: typeof DemoRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  DashboardAccountRoute: typeof DashboardAccountRoute
  DashboardAdminRoute: typeof DashboardAdminRouteWithChildren
  DashboardBillingRoute: typeof DashboardBillingRoute
  DashboardInstallRoute: typeof DashboardInstallRoute
  DashboardRedeemRoute: typeof DashboardRedeemRoute
  DashboardReferralsRoute: typeof DashboardReferralsRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
  RTokenRoute: typeof RTokenRoute
  VsMarkerRoute: typeof VsMarkerRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  ApiPublicFeedbackRoute: typeof ApiPublicFeedbackRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
  DashboardProjectsProjectIdRoute: typeof DashboardProjectsProjectIdRoute
  DashboardProjectsNewRoute: typeof DashboardProjectsNewRoute
  ApiPublicWidgetConfigTokenRoute: typeof ApiPublicWidgetConfigTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/changelog': {
      id: '/changelog'
      path: '/changelog'
      fullPath: '/changelog'
      preLoaderRoute: typeof ChangelogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vs/marker': {
      id: '/vs/marker'
      path: '/vs/marker'
      fullPath: '/vs/marker'
      preLoaderRoute: typeof VsMarkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$token': {
      id: '/r/$token'
      path: '/r/$token'
      fullPath: '/r/$token'
      preLoaderRoute: typeof RTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/referrals': {
      id: '/dashboard/referrals'
      path: '/dashboard/referrals'
      fullPath: '/dashboard/referrals'
      preLoaderRoute: typeof DashboardReferralsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/redeem': {
      id: '/dashboard/redeem'
      path: '/dashboard/redeem'
      fullPath: '/dashboard/redeem'
      preLoaderRoute: typeof DashboardRedeemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/install': {
      id: '/dashboard/install'
      path: '/dashboard/install'
      fullPath: '/dashboard/install'
      preLoaderRoute: typeof DashboardInstallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/billing': {
      id: '/dashboard/billing'
      path: '/dashboard/billing'
      fullPath: '/dashboard/billing'
      preLoaderRoute: typeof DashboardBillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/dashboard/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/account': {
      id: '/dashboard/account'
      path: '/dashboard/account'
      fullPath: '/dashboard/account'
      preLoaderRoute: typeof DashboardAccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/projects/new': {
      id: '/dashboard/projects/new'
      path: '/dashboard/projects/new'
      fullPath: '/dashboard/projects/new'
      preLoaderRoute: typeof DashboardProjectsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/projects/$projectId': {
      id: '/dashboard/projects/$projectId'
      path: '/dashboard/projects/$projectId'
      fullPath: '/dashboard/projects/$projectId'
      preLoaderRoute: typeof DashboardProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin/users': {
      id: '/dashboard/admin/users'
      path: '/users'
      fullPath: '/dashboard/admin/users'
      preLoaderRoute: typeof DashboardAdminUsersRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/codes': {
      id: '/dashboard/admin/codes'
      path: '/codes'
      fullPath: '/dashboard/admin/codes'
      preLoaderRoute: typeof DashboardAdminCodesRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/api/public/stripe-webhook': {
      id: '/api/public/stripe-webhook'
      path: '/api/public/stripe-webhook'
      fullPath: '/api/public/stripe-webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/feedback': {
      id: '/api/public/feedback'
      path: '/api/public/feedback'
      fullPath: '/api/public/feedback'
      preLoaderRoute: typeof ApiPublicFeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/widget-config/$token': {
      id: '/api/public/widget-config/$token'
      path: '/api/public/widget-config/$token'
      fullPath: '/api/public/widget-config/$token'
      preLoaderRoute: typeof ApiPublicWidgetConfigTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface DashboardAdminRouteChildren {
  DashboardAdminCodesRoute: typeof DashboardAdminCodesRoute
  DashboardAdminUsersRoute: typeof DashboardAdminUsersRoute
}

const DashboardAdminRouteChildren: DashboardAdminRouteChildren = {
  DashboardAdminCodesRoute: DashboardAdminCodesRoute,
  DashboardAdminUsersRoute: DashboardAdminUsersRoute,
}

const DashboardAdminRouteWithChildren = DashboardAdminRoute._addFileChildren(
  DashboardAdminRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChangelogRoute: ChangelogRoute,
  DemoRoute: DemoRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  DashboardAccountRoute: DashboardAccountRoute,
  DashboardAdminRoute: DashboardAdminRouteWithChildren,
  DashboardBillingRoute: DashboardBillingRoute,
  DashboardInstallRoute: DashboardInstallRoute,
  DashboardRedeemRoute: DashboardRedeemRoute,
  DashboardReferralsRoute: DashboardReferralsRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
  RTokenRoute: RTokenRoute,
  VsMarkerRoute: VsMarkerRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  ApiPublicFeedbackRoute: ApiPublicFeedbackRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
  DashboardProjectsProjectIdRoute: DashboardProjectsProjectIdRoute,
  DashboardProjectsNewRoute: DashboardProjectsNewRoute,
  ApiPublicWidgetConfigTokenRoute: ApiPublicWidgetConfigTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
